### PR TITLE
Updated pages

### PR DESCRIPTION
**Pull request by Eqnerret**
Updated frontend codes for Login, admin logs, account management, and landing page

### CODE REVIEW

**Review by Adotey2 — APPROVED** [review]
It seems fine let's go ahead

**Review by oswaldamoah — APPROVED** [review]

**Review by thejeveloper — APPROVED** [review]
I approve 🤞🏿

**Review by thejeveloper — APPROVED** [review]
I approve 🤞🏿🤞🏿

**Review by thejeveloper — APPROVED** [review]

**Review by thejeveloper — APPROVED** [review]
good

**Review by thejeveloper — APPROVED** [review]

**Review by thejeveloper — APPROVED** [review]

**Review by thejeveloper — APPROVED** [review]

**Review by theboyshirvon — APPROVED** [review]

**Review by oswaldamoah — APPROVED** [review]

**Pull request merged**
